// Pronounce
export const FETCH_PRONOUNCE = 'regions/FETCH_PRONOUNCE'
export const RECEIVE_PRONOUNCE = 'regions/RECEIVE_PRONOUNCE'

// 50 Characters
export const FETCH_50_CHARACTERS = 'characters/FETCH_50_CHARACTERS'
export const RECEIVE_50_CHARACTERS = 'characters/RECEIVE_50_CHARACTERS'

// Pronunciations One
export const FETCH_PRONUNCIATIONS_ONE = 'pronunciationsOne/FETCH_PRONUNCIATIONS_ONE'
export const RECEIVE_PRONUNCIATIONS_ONE = 'pronunciationsOne/RECEIVE_PRONUNCIATIONS_ONE'
export const SELECT_PRONUNCIATIONS_ONE = 'pronunciationsOne/SELECT_PRONUNCIATIONS_ONE'

export const PRONUNCIATIONS_ONE_FETCH = 'pronunciationsOne/PRONUNCIATIONS_ONE_FETCH'
export const PRONUNCIATIONS_ONE_REQUEST = 'pronunciationsOne/PRONUNCIATIONS_ONE_REQUEST'
export const PRONUNCIATIONS_ONE_SUCCESS = 'pronunciationsOne/PRONUNCIATIONS_ONE_SUCCESS'
export const PRONUNCIATIONS_ONE_FAILURE = 'pronunciationsOne/PRONUNCIATIONS_ONE_FAILURE'

// Pronunciations Two
export const FETCH_PRONUNCIATIONS_TWO = 'pronunciationsTwo/FETCH_PRONUNCIATIONS_TWO'
export const RECEIVE_PRONUNCIATIONS_TWO = 'pronunciationsTwo/RECEIVE_PRONUNCIATIONS_TWO'
export const SELECT_PRONUNCIATIONS_TWO = 'pronunciationsTwo/SELECT_PRONUNCIATIONS_TWO'

// Greetings
export const FETCH_GREETINGS = 'greetings/FETCH_GREETINGS'
export const RECEIVE_GREETINGS = 'greetings/RECEIVE_GREETINGS'
